version: '3'
services:
  capsit_db:
    image: postgres:14.1
    container_name: capsit_postgres
    environment:
      POSTGRES_USER: capsit
      POSTGRES_PASSWORD: capsit
      POSTGRES_DB: capsit
    ports:
      - 5432:5432
    volumes:
      - "$HOME/docker/capsit/postgres/data:/var/lib/postgresql/data"

  pgAdmin:
        image: dpage/pgadmin4
        container_name: pg-admin
        environment:
            - PGADMIN_DEFAULT_EMAIL=pgadmin@test.com
            - PGADMIN_DEFAULT_PASSWORD=123456789
        ports:
            - 8050:80   
        volumes:
                - "$HOME/docker/pgadmin:/var/lib/pgadmin"
